### ISSUE TITLE
train和val数据集怎么划分啊？我用的KITTI官网下载的数据集

### ISSUE THREAD

**Issue by WQ-2001-mc** [shreydan/yolo-object-detection-kitti#1]
train和val数据集怎么划分啊？我用的KITTI官网下载的数据集

**Comment by shreydan** [comment]
sorry, I am not sure about the KITTI website dataset, I got my dataset from: [https://www.kaggle.com/datasets/klemenko/kitti-dataset](https://www.kaggle.com/datasets/klemenko/kitti-dataset)

抱歉，我不确定 KITTI 网站数据集，我的数据集来自 [https://www.kaggle.com/datasets/klemenko/kitti-dataset](https://www.kaggle.com/datasets/klemenko/kitti-dataset)
